import Link from "next/link";

export default function DisclaimerPage() {
  return (
    <main className="min-h-screen bg-[#101020] px-6 py-16 text-white">
      <section className="mx-auto max-w-3xl">
        <Link href="/" className="text-sm text-white/50">
          ← Back to Home
        </Link>

        <h1 className="mt-10 text-5xl font-bold">Disclaimer</h1>

        <div className="mt-8 space-y-6 leading-8 text-white/70">
          <p>
            SoulLoop is designed for entertainment, symbolic reflection, and
            self-discovery only.
          </p>

          <p>
            SoulLoop uses AI to generate reflections inspired by Eastern wisdom,
            I Ching-style thinking, Bagua, Yin-Yang, Five Elements, and
            Zi Wei Dou Shu-style life-theme language. It does not perform real
            divination, cast actual hexagrams, calculate BaZi charts, or generate
            Zi Wei Dou Shu charts.
          </p>

          <p>
            SoulLoop does not provide medical, legal, financial, psychological,
            or other professional advice.
          </p>

          <p>
            The readings generated by SoulLoop are symbolic and should not be
            used as the sole basis for important life decisions.
          </p>

          <p>
            If you are facing a serious medical, legal, financial, or emotional
            issue, please seek help from a qualified professional.
          </p>
        </div>
      </section>
    </main>
  );
}